<?php include_once 'header1.php' ?>
<style>
    .p {
        margin-left: 10px;
    }
</style>
<div class="container mt-5">
    <h2>Terms of Use</h2>
    <p>The Life Eternal Trust ( the Trust), is a Charitable Trust, registered with the Charity Commissioner, Mumbai under Registration No E 4884 (B) 1972 and having its registered office at B-612, Urmila Co-op. Hsg. Soc.,Koldongri, Andheri – East,Mumbai – 400 069.The Trust is the owner of the website www.sahajayogamumbai.org. From here onwards, in this document the term Trust refers to the website www.sahajayogamumbai.org.</p>
    <p> <strong>1. Acceptance of Terms:</strong>
        <br>This Web- Site is offered to the user of the Service (User) on the condition that the User accepts the terms contained herein, without any modification whatsoever. For the purposes of this Terms of Use, ‘Service’ shall mean and include, without limitation, access to all, one or some of the following: – HTML Code, literature, information, software, products, tools and services including tools and information (which help persons take decisions to donate monies and/or give time to non-governmental organizations or for charitable causes), provided or made available on www.sahajayogamumbai.org, whether pursuant to subscription or otherwise.
    </p>
    <p><strong>2. Intellectual Property Rights:</strong>
        <br> www.sahajayogamumbai.org hereby grants to the User, the right to use the Service in accordance with these terms, and for no other purpose. Please note that all elements contained on this Web-Site including all individual articles, columns and other elements making up the Service are also Copyrighted works and are owned by The Life Eternal Trust, Mumbai /www.sahajayogamumbai.org ) and/ or its Suppliers and are protected by Copyright, Service Marks and Trademark laws, International Treaty provisions and/or other proprietary rights under the laws of India and this Terms of Use.The Life Eternal Trust, a charitable organisationhas provided the rights to use all elements of this service protected by copyright, service marks and Trademark laws to www.sahajayogamumbai.org. By using the service you agree to abide by all applicable Copyright and other laws as well as any additional Copyright notices or restrictions contained in the Service. www.sahajayogamumbai.org or other third parties including www.sahajayogamumbai.org shall be entitled to obtain equitable relief for any violation of their IP, over and above all other remedies available to it to protect its interests therein. Violators will be liable to be prosecuted to the maximum extent possible. Copying for reproduction, for redistribution or other purpose of the web site or any part thereof including but not limited to text content and graphics to any other server or location including caching of any kind is expressly prohibited. The Service is licensed to the User not sold to him. www.sahajayogamumbai.org owns the Service, its applications and Trademarks.
    </p>
    <p><strong>3. Links to third Party Sites:</strong>
        <br> This Web- Site may contain links to Web Sites operated by parties other than www.sahajayogamumbai.org. The links in this Site will let the User leave www.sahajayogamumbai.org and proceed to the linked site. The User’s use of each such site is also subject to these Terms of Use and other terms of use, if any, contained within each such site. In the event that any of the Terms contained herein conflict with the terms of use contained within any such site, then the terms of use for such site shall prevail. The linked Sites are not under the control of www.sahajayogamumbai.org and www.sahajayogamumbai.org is not responsible for the contents of any linked Site or any link contained in a linked Site, or any changes or updates to such sites. www.sahajayogamumbai.org will not directly or indirectly be liable for any loss that may arise to the User as a result of his accessing the linked Sites.
    </p>
    <p><strong>4. Access Restriction/Fees:</strong>
        <br>
        www.sahajayogamumbai.org reserves the right to deny, in its sole discretion, any User access to this Web Site or any portion thereof without notice or justification. Further www.sahajayogamumbai.org reserves the right at any time to charge fees for access to any service provided by it. It shall put up a notice to this effect with necessary details at the relevant point of time.
    </p>

    <p><strong>5. Limits on Personal and Non-Commercial Use:
        </strong><br>
        The User expressly agrees to use the Service strictly for personal purpose. The User shall not recompile, disassemble, copy, modify, distribute, transmit, display, perform, reproduce, publish or create derivative works from, transfer, or sell any information, software, products, tools or services accessed from this web site. The User may not rent, lease, sell, sublicense, lend or in any manner allow any other party to use the Service, with or without consideration.</p>
    <p><strong>6. Privacy:</strong><br>
        The User represents that he is aware that in the process of subscribing to the Service or parts of it, www.sahajayogamumbai.org may obtain information relating to the User, including that of a confidential nature. This information will be used by www.sahajayogamumbai.org for its internal purposes and will be kept confidential. Notwithstanding anything contained above, www.sahajayogamumbai.org reserves the right to disclose personal information where it believes in good faith that such disclosure is required by law, to perform necessary credit checks or collect or report debts owed to www.sahajayogamumbai.org, to protect www.sahajayogamumbai.org’s rights or property or for other bonafide uses. The User agrees and warrants that all information that www.sahajayogamumbai.org may possess or may obtain pursuant to the use of Service has been possessed or obtained with the permission of the User.</p>
    <p><strong>7. Modification of these terms and conditions:</strong><br>
        www.sahajayogamumbai.org reserves the right to change, without notice, this Terms of Use under which the Service is offered. The User’s continued use of the Service will be subject to the Terms of Use in force at the time of the Use.</p>
    <p><strong>8. Indemnification:</strong><br>
        The User agrees to indemnify, defend and hold harmless www.sahajayogamumbai.org, its officers, directors, employees, representatives and agents, any third party providers, distributors from and against any cause of action ,claim or demand, including without limitation any reasonable legal, accounting or other professional fees, brought by or on the user’s behalf in excess of the liability described herein or by / on account of a third party due to or arising out of User’s use of this Web site, the Service contained herein, the violation of any intellectual property or any other right of any person or entity.</p>
    <p><strong>9. Disclaimer of warranties:</strong><br>
        www.sahajayogamumbai.org warrants that it does not provide any Professional Financial advice on this web site. <br>
        The User warrants that it shall obtain independent advice before making any Financial or other decision based on the service provided through this website. <br>
        www.sahajayogamumbai.org expressly disclaims all warranties and conditions of any kind, whether express, implied or statutory pertaining to the Services provided by it including but not limited to implied warranties and conditions of merchantability, fitness for a particular purpose, data accuracy and completeness and any warranties relating toviruses and non-infringement in the Service and provision of service free from disruption or interruption. <br>
        The Service should not be construed to be an advertisement for solicitation for Donations for non-governmental organizations or other charitable organizations listed in this website. <br>
        www.sahajayogamumbai.org shall not be responsible for any loss or liability incurred to the user as a consequence of his or any other person on his behalf taking any financial, investment or other decisions based on the information, research reports, analysis, etc. provided on the web site. <br>
        www.sahajayogamumbai.org shall also not be liable for errors, omissions or typographical errors, disruption delay, interruption, failure, deletion or defect of/in the Service provided by it. <br>
        www.sahajayogamumbai.org shall not be liable, directly or indirectly, to the User or any third party, as a consequence of the failure of its equipment, howsoever defined, or that ofInternet Service Provider, User or any third party to function in such manner as is reasonably expected of such equipment. www.sahajayogamumbai.org shall not be responsible for any downtime of such equipment. <br>
        www.sahajayogamumbai.org makes no representations or warranties, either express or implied that the research, development, marketing, distribution, use or provision of the Service will not infringe any patent, copyright or other right of any third party.</p>
    <p><strong>10. Limitation of liability:</strong> <br>

        The User agrees that neither www.sahajayogamumbai.org nor its Trustees, directors or employees shall be liable for any direct, indirect, incidental, special or consequential damages, resulting from the use/delivery/performance or the inability to use/deliver/perform the Service or for cost of procurement of substitute goods and repair & correction services or resulting from the Services subscribed to or obtained or messages received or transactions entered into through or of User’s transmissions or data, even if www.sahajayogamumbai.org or its employees have been advised of the possibility of such damages.
        The User further agrees that www.sahajayogamumbai.org shall not be liable for any damages arising from interruption, suspension or termination of Service, whether such interruption, suspension or termination was justified or not, negligent or intentional, inadvertent or advertent.
        The User also agrees that his sole remedy under this Terms of Use is cancellation of the Service.</p>

    <p><strong>11. Submissions:</strong><br>
        Visitor agrees as a condition of viewing, that any communication between Visitor and Website is deemed a submission. All submissions, including any data, queries, feedback, ideas, comments or suggestion shall become the exclusive property of the Website or its affiliates and may be used, without further permission, for commercial use without additional consideration of any kind.</p>
    <p><strong>12. Monitoring:</strong><br>
        We have the right, but not the obligation, to monitor any activity and content associated with the website(s) and/or the services. We may investigate any reported violation of these Conditions or complaints and take any action that we deem appropriate (which may include, but is not limited to, issuing warnings, suspending, terminating or attaching conditions to your access and/or removing any materials on the website(s) and/or the services.</p>
    <p><strong>13. Governing Law and Jurisdiction:</strong> <br>
        This Terms of Use is governed by the laws of the Republic of India. The User hereby consents and submits to the exclusive jurisdiction and venue of Courts in Mumbai, India in all disputes arising out of or relating to the use of this Web site or Service.</p>
    <p> <strong>14. General:</strong><br>
    <div class="container ml-3">
        <p><strong>a.</strong> You agree to use this website only for lawful purposes, and in a manner which does not infringe the rights of www.sahajayogamumbai.org or any third party or the use and enjoyment of the site by any third party.</p>
        <p><strong>b.</strong> Except for death or personal injury arising through our negligence, www.sahajayogamumbai.org shall in no event be liable for any damages including, without limitation, direct, indirect or consequential damages, whatsoever arising from or in connection with the use or loss of use of the website, or any content on the website.</p>
        <p><strong>c.</strong> www.sahajayogamumbai.orgcan change these Terms and Conditions at any time by posting changes online under this section “Terms and Conditions”. Your continued use of this site after changes have been posted constitutes acceptance of the modified terms.</p>
        <p><strong>d.</strong> www.sahajayogamumbai.org does not guarantee that the site’s facilities and functions will be free from error or uninterrupted, that the site or the server that makes it available to you are free of viruses or bugs, that defects will be corrected, or that the content on the website is accurate or complete.</p>
        <p><strong>e.</strong> www.sahajayogamumbai.orgtakes no responsibility for the content of external Internet sites linked to or cited on this website.</p>
        <p><strong>f.</strong> Any communication or material that you transmit to, or post on any public area of this website will be treated as non-confidential and non-proprietary information unless otherwise stated by www.sahajayogamumbai.org . We reserve the right to remove without notice any material posted in any public area of the website.</p>
        <p><strong>g.</strong> Copyright- Materials featured on this site may be reproduced free of charge in any format or media without requiring specific permission. This is subject to the material being reproduced accurately and not being used in a derogatory manner or in a misleading context. Where the material is being published or issued to others, the source must be prominently acknowledges. However, the permission to produce this material does not extend to any material on this site, which is explicitly identified as being the copyright of a third party. Authorisation to reproduce such material must be obtained from the copyright holders concerned.</p>
        <p><strong>h.</strong> Hyperlinking Policy- We do not object to you linking directly to the information that is hosted on our site and no prior permission is required for the same. However, we would like you to inform us about any links provided to our site so that you can be informed of any changes or updates therein. Also, we do not permit our pages to be loaded into frames on your site. Our Department pages must load into a newly opened browser window of the user.</p>
        <p><strong>i.</strong> Governing Law/Dispute Resolution : The terms and conditions shall be governed in accordance with the laws of India and the Courts in Mumbai shall have the exclusive jurisdiction to try and suit, proceedings in connection therewith/in that behalf. Any disputes under this agreement, which cannot be settled by negotiation may be resolved exclusively by arbitration and shall be held in Mumbai, India and conducted in accordance with the provision of Arbitration and Conciliation Act, 1996 or any statutory modification or re-enactment thereof. Subject to the above, the courts of law at Mumbai alone shall have the jurisdiction in respect of all matters connected with the agreement. The arbitration award shall be final and binding.</p>
        <p><strong>j.</strong> If you do not accept these Terms and Conditions in full, you must stop using this website immediately. We reserve the right to prevent you accessing this website, without prejudice to any of our other rights, if we consider that you have contravened any of these Terms and Conditions.</p>
        <p><strong>k.</strong> Nothing contained in this Terms of Use is in derogation of www.sahajayogamumbai.org’s right to comply with Governmental, Court and Law enforcement requests or requirements relating to use of this Web site, Service or information provided to or gathered by www.sahajayogamumbai.org with respect to such use.</p>
        <p><strong>l.</strong> This Terms of Use constitutes the entire agreement between the User and www.sahajayogamumbai.org with respect to this Web site and the Services provided by www.sahajayogamumbai.org.</p>
        <p><strong>m.</strong> If the User violates any term of this Terms of Use, www.sahajayogamumbai.org may terminate the User’s access to this Web -Site, without waiving any other rights. The User would continue to remain liable for any liabilities that may have arisen before the termination.</p>
        <p><strong>n.</strong> www.sahajayogamumbai.orgalso reserves the right, at its sole discretion, to change the Terms and Conditions at any time by posting changes online, and any changes that www.sahajayogamumbai.orgmakes to the Terms and Conditions will be effective immediately upon posting. Your continued use of this site after changes means you agree to be legally bound by these terms as updated and/or amended.</p>
        <p><strong>o.</strong> www.sahajayogamumbai.orgdoes not guarantee that the Site or the server that hosts it is functional, uninterrupted, accurate, reliable or free from viruses and bugs. Further, www.sahajayogamumbai.orgreserves the right, at any time, to modify or discontinue, temporarily or permanently, the Site (or any part thereof) without notice. You agree that www.sahajayogamumbai.org shall not be liable to you or to any third party for any modification, suspension, or discontinuance of the Site, or of any Materials (as defined below).</p>
        <p><strong>p.</strong> www.sahajayogamumbai.orgdoes its utmost to ensure the site is functional and that all material contained in the site is accurate. However, www.sahajayogamumbai.orgmakes available the information and materials on the Site (the ‘Materials’) for general informational purposes only, and www.sahajayogamumbai.orgdoes not represent or warrant that the Materials are accurate, complete or current. www.sahajayogamumbai.orgshall not have any liability whatsoever, howsoever arising, in respect of any use which you make of the Site and/or the Materials. You are advised to verify the accuracy of all Materials before relying on them, and any reliance you place on it is done so at your own risk.</p>
        <p><strong>q.</strong> This Site contains links to other websites which are not maintained by www.sahajayogamumbai.org. www.sahajayogamumbai.orgis not responsible for the content of these sites and does not accept responsibility or liability for the operation and content of such sites. The inclusion of any link to such sites is for your convenience and does not imply association or endorsement by www.sahajayogamumbai.orgunless otherwise stated.</p>
        <p><strong>r.</strong> Reasonable efforts have been made at the time of publishing each page to examine the contents of each organisation and publication linked to on this website, but www.sahajayogamumbai.orgtakes no responsibility for the contents contained on such links, or the manner in which such websites are operated.</p>
        <p><strong>s.</strong> No third party is permitted to link any other website to this website without first obtaining the express consent of www.sahajayogamumbai.org.</p>
        <p><strong>t.</strong> If there is any conflict between these terms and the rules and/or specific terms of use appearing on specific sections of the website, then the latter shall prevail.</p>
        </p>
    </div>
    <p><strong>15. Donations :</strong><br>
        The online donations through credit/debit cards/ Net Banking should be used only for making donations / contributions to the The Life Eternal Trust. In case you wish to make your contribution to us for any other purpose, please use the cheque/payorder/DD method. <br>
        All donations accepted through on line methods will be accounted for as the income of the Trust and will be applied for the charitable purposes they are meant for. However, if the donor wishes to make a Corpus donation then he should only use the cheque/payorder/DD method and state specifically in his covering letter that the donation is meant as contribution to the Corpus of the trust. In the absence of such specific direction, the donation will be accounted for as income of the Trust by the Income Tax Dept. <br>
        The facility of making on line donations is currently restricted to Indian nationals and Indian organisations, in Indian rupees only. Please note that the credit /debit cards issued outside India are currently not eligible to be used for online donations. <br>
        All donations will be accepted as donations meant for the various activities being undertaken by the Trust(Purpose-General) unless the donor specifies the purpose for which the donation should be used. <br>
        The Trust will be sending a receipt for the donation made to the address indicated on the registration form within 45 days of receiving the payment.Please contact the trust by email or post in case you do not receive the receipt in the time indicated. <br>
        Please note that there is a levy charged by the Bank/Card companies on the on line donation made through credit/debit card. As a result, in such cases, the receipt issued by the Trust will be for the amount net of this levy. <br>
        All donors making a donation of more than Rs 10,000/- are, required to give their PAN number on the registration form.
        The donors are most welcome to re-assure themselves that their donations have been used for the purpose they have specified. In this connection, they may contact the trust. In the case of donations exceeding Rs 10 lacs, the trust will be able to provide an audited certificate of end use if so requested by the donor.</p>
    <p><strong>16. Payment Gateway :</strong><br>
        If you are making donations through the payment gateway, you understand that the payment gateway is provided by a third party and governed by the terms and conditions provided by such third party. You are liable in the event you violate any of the terms and conditions of such third party in making your donations. The Trust shall not be responsible for any such errors or default in making your donations.</p>
    <p><strong>17. Donation Information, Delivery, Refund & Cancellations:</strong><br>
Before making any donation, you are required to fill up all the mandatory information in the donation form. This information will be used for further communication in terms of tax exemption certificates, feedback reports etc. And also note that this is required as per Government of India order to record all the information about the donors. <br>
You can donate to selected causes on the Trust using a number of payment methods such as credit or debit cards or cheque. Donations are processed by our payment gateway service provider ICICI Merchant Services. <br>
The Trust reserves the right at any time from time to time to modify or discontinue, temporarily or permanently the donation facility with or without notice. <br>
Donations made through the Trust are NON-REFUNDABLE. Please contact the Trust immediately if there are justifying reasons or circumstances for refund and your case may be reviewed on a best effort basis and decision of the Trust will be final. <br>
In case of an unlikely event of an erroneous deduction or if the donor wants to cancel/deduct the donation, The Trust will refund the wrongly deduced amount within 30 days from the date of receiving the complaint/request from the donor.We would require a proof of deduction of the donated amount and a written request for refund. <br>
In such cases if the receipt already has been issued, then the donor needs to return the original receipt at our registered address.</p>
<p> <strong>18. Prohibited Activity:</strong><br>
You agree to act in a responsible and legal manner when using the Trust website. You shall comply with all applicable laws, regulations and rules and undertake not to use the Trust website for any unlawful purpose or in a manner which is likely to cause harm or offense any other user including the Trust. <br>
You agree not to create a false identity on the website, impersonate any person or entity (including members of the Trust) or falsely state or otherwise misrepresent yourself, your name, your age or your affiliation with any person or entity; <br>
You agree not to submit or transmit through any material that contains viruses or any other computer codes, files or programs that interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment, or otherwise permit the unauthorized use of a computer or computer network; <br>
The Trust reserves the right to investigate and take appropriate legal action against anyone who, in the Trust’s opinion, violates this provision, including, without limitation, reporting you to appropriate law enforcement authorities.</p>
</div>
<?php include_once 'footer.php' ?>